[global]
exclude-files = [
    "src/main.rs",
    "src/docs/*"
]
target-dir = ".tarpaulin"
run-types = ["Tests"]
timeout = "1m"

ignore-tests = false
skip-clean = true
verbose = true
line = true

jobs = 4
fail-under = 93

[report]
output-dir = "coverage"
out = ["Xml"]