name: Build

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:8.0-noble
        ports:
          - 27017:27017

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Check code
      run: cargo check --verbose

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Build
      run: cargo build --verbose

    - name: Execute tests
      run: cargo test -- --test-threads=1
