name: CI

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y curl build-essential pkg-config

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      id: toolchain
      with:
        toolchain: stable
        components: rust-src

    - name: Check code
      run: cargo check --verbose

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose --test-threads=1
